name: workflow agent (py)
on: push

jobs:
  langgraph:
    runs-on: ubuntu-latest
    environment: openrouter
    env:
      API_KEY: ${{secrets.API_KEY}}
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest langchain_test.py
          tests: py/tests
          extras: langchain
          version: 3.12